on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/12 * * *"
jobs:
  run-epl-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
       
      - name: Install required libraries
        run: |
          python -m pip install requests plotly
      - name: Run Python script
        run: |
          python assets/charts/epl.py
      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add assets/charts/genero.html
          git add assets/charts/idiomas.html
          git add assets/charts/publicacion.html
          git commit -m "Update date to $(date +%Y-%m-%d)" || echo "No changes to commit"
      - name: Push changes
        run: git push
